services:
  api:
    image: ghcr.io/saleor/saleor:3.23
    
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    stdin_open: true
    tty: true
    depends_on:
      - db
      - cache
      - jaeger
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
    env_file:
      - common.env
      - backend.env
    environment:
      - DASHBOARD_URL=https://saleor.prsn.in/
      - ALLOWED_HOSTS=apisaleor.prsn.in,localhost,127.0.0.1,api
      - WEB_CONCURRENCY=8

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:3.23
    
    restart: unless-stopped
    environment:
      - API_URL=https://apisaleor.prsn.in/graphql/

  db:
    image: library/postgres:15-alpine
    
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql:ro,z
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  cache:
    image: valkey/valkey:8.1-alpine
    
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-cache:/data

  worker:
    image: ghcr.io/saleor/saleor:3.23
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file:
      - common.env
      - backend.env
    depends_on:
      - cache
      - mailpit
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media

  jaeger:
    image: jaegertracing/jaeger
    
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - type: tmpfs
        target: /tmp

  mailpit:
    image: axllent/mailpit
    
    restart: unless-stopped
    networks:
      - saleor-backend-tier

volumes:
  saleor-db:
    driver: local
  saleor-cache:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge
